version: "3.8"

services:
  api:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: ai-invoice-agent-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data/preprocessed:/tmp/preprocessed
    restart: unless-stopped
